### ISSUE TITLE
How to input .csv file instead. nc

### ISSUE THREAD

**Issue by akashsinghraghuvanshi** [tammasloughran/ehfheatwaves#12]
I am working on seperate multiple stations which are all clubbed in a single .csv file. How Can I incorporate .csv instead. nc. Also summer in my region (India-NH) extends from March mid to October. How to include these seasons. Please Help

**Comment by tammasloughran** [comment]
Hi there,

To my understanding, a .csv file is just a plain text encoded file with some commas or semicolons to separate values. Because there is no strict formatting standards for .csv files (i.e. what metadata is in the header and the layout of the data in the csv file) it would be too difficult for ehfheatwaves to account for every possible formatting used by every data product. So I really can't write an interface for plain text files and satisfy everyone (or even anyone).

If you insist on using only csv, you will have to do this yourself and calculate the base period yourself. There are many python libraries that allow you to lead in raw data from csv file into a numpy 2d numpy array. For example you could use numpy's numpy.genfromtxt(), or perhaps pandas if you want to preserve the metadata in the file into a pandas dataframe.

Otherwise it might simply be a better idea to simply convert your station data into a netcdf file. I.e. have each station on a single spatial dimension, with their lat and lon as a separate variables rather than dimensions. The time dimension should be the same size for all stations. Data must exist for all stations in the base period and have nan for missing vlaues if the stations span different periods. I have done this before and it's not too difficult if you are familiar with creating netcdf files with python's netcdf4 package. I should have an example file somwhere, but I would need to dig into my archives to find it.

Cheers,
Tam

**Comment by akashsinghraghuvanshi** [comment]
Thank you sir for your valuable suggestions..This will definitely going to help me out in carrying forward my work

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Apr 2022 at 9:47 am, Tammas ***@***.***> wrote:   


Hi there,

To my understanding, a .csv file is just a plain text encoded file with some commas or semicolons to separate values. Because there is no strict formatting standards for .csv files (i.e. what metadata is in the header and the layout of the data in the csv file) it would be too difficult for ehfheatwaves to account for every possible formatting used by every data product. So I really can't write an interface for plain text files and satisfy everyone (or even anyone).

If you insist on using only csv, you will have to do this yourself and calculate the base period yourself. There are many python libraries that allow you to lead in raw data from csv file into a numpy 2d numpy array. For example you could use numpy's numpy.genfromtxt(), or perhaps pandas if you want to preserve the metadata in the file into a pandas dataframe.

Otherwise it might simply be a better idea to simply convert your station data into a netcdf file. I.e. have each station on a single spatial dimension, with their lat and lon as a separate variables rather than dimensions. The time dimension should be the same size for all stations. Data must exist for all stations in the base period and have nan for missing vlaues if the stations span different periods. I have done this before and it's not too difficult if you are familiar with creating netcdf files with python's netcdf4 package. I should have an example file somwhere, but I would need to dig into my archives to find it.

Cheers,
Tam
