### ISSUE TITLE
ValueError: did not find HDF5 headers

### ISSUE THREAD

**Issue by salitchakma** [tammasloughran/ehfheatwaves#27]
Hi Tam,

I have been running `pip install .` and failing to install the dependencies so far. With many [suggestions](https://stackoverflow.com/questions/57802076/cannot-install-netcdf4-by-pip-on-windows) from different forums, I already tried python version 3.11.4, 3.8.10, and 3.8.0. but lo success.

This is not an issue with the code but just wondering if you could have a look and see what is wrong.

Thanks,
Salit

The error I am getting on git bash is:
```
Processing c:\users\salit.chakma\ehfheatwaves
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.8.0 (from ehfheatwaves==1.1.5)
  Using cached numpy-1.21.6-cp37-cp37m-win32.whl (11.7 MB)
Collecting pandas (from ehfheatwaves==1.1.5)
  Using cached pandas-1.3.5-cp37-cp37m-win32.whl (8.9 MB)
Collecting netcdf4 (from ehfheatwaves==1.1.5)
  Using cached netCDF4-1.6.4.tar.gz (778 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      reading from setup.cfg...

          HDF5_DIR environment variable not set, checking some standard location
s ..
      checking C:\Users\salit.chakma\include ...
........
......
 ValueError: did not find HDF5 headers
```

**Comment by salitchakma** [comment]
So, I solved it by downloading wheel file for the python version (3.7 at this moment) I am using. It was requiring to cftime to be installed, which was in turn asking to install C++ build tool. To get around, I downloaded cftime wheel file. And it worked - been able to install all dependencies.

**Comment by tammasloughran** [comment]
Thanks @salitchakma , for a bit more explanation: wheel files are just .zip files with the required code and libraries.
Rather than installing a separate python package, it may have been better to install the official netCDF libraries for windows https://downloads.unidata.ucar.edu/netcdf/. (netcdf is a subset of HDF5, so would come with the required HDF5 libraries.)
I redacted the link to the wheel file you used, since I don't trust unofficial sources. Pre-built wheel distributions for packages can be obtained from pypi, for example https://pypi.org/project/cftime/#files .

**Comment by salitchakma** [comment]
Thank you, @tammasloughran. Perhaps the use of the unofficial wheels are the reason why I was unable open the output nc files as xarray dataset? I am going to update the packages with the official one and give it another go.
